[pytest]
#in addopts this line will be by default run on the terminal and will generate the reports
addopts =
    -ra
    --clean-alluredir
    --html=reports/report.html
    --self-contained-html
    --alluredir=reports/allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO
markers =
    smoke: small set of critical tests
    regression: full regression suite
    module_ap: Analytic Plan Module tests
    module_ps: Project Specs Module tests
    module_ads: Analytic Dataset Module tests
    module_mm: Main Model tests
    module_wb: Workbook tests
    module_ai: Activate Input tests
